[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311", "py312", "py313"]
extend-exclude = "^/source/__pycache__/"

[tool.isort]
profile = "black"
line_length = 100
skip = ["source/__pycache__"]

[tool.ruff]
line-length = 100
target-version = "py38"
exclude = ["source/__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
